modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/BlueDuckYT/The-Outer-End/issues"
[[mods]]
modId="outer_end"
version="0.2.15"
displayName="The Outer End"
credits="Developed by Blue Duck, LudoCrypt, MooseOnTheRocks, GiantLuigi4, and RedRoseWarrior1"
authors="A lot of people"
description='''The Outer End is an end mod'''
[[dependencies.outer_end]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.outer_end]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.outer_end]]
modId = "blueprint"
mandatory = false
versionRange = "5.5.0"
ordering = "BEFORE"
side = "BOTH"