modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/BlueDuckYT/The-Outer-End/issues"
[[mods]]
modId="outer_end"
version="0.2.9"
displayName="The Outer End"
credits="Developed by Blue Duck, LudoCrypt, MooseOnTheRocks, and GiantLuigi4"
authors="A lot of people"
description='''
The Outer End is an end mod
'''
[[dependencies.outer_end]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.outer_end]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.outer_end]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.4,)"
    ordering="NONE"
    side="BOTH"